name: 'Publish docker image'
description: 'This action publishes a docker image for valid tags'
inputs:
  push_also_tag:
    description: 'Tag to be also pushed.'
    required: false
  docker_user:
    description: 'Username with push access to docker registry.'
    required: true
  docker_token:
    description: 'Token for user with push access to docker registry.'
    required: true
  tag:
    description: 'Upload image under additional tag (e.g. latest).'
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Login to docker hub
      id: login-to-docker-hub
      run: |
        echo "Login to docker registry...";
        export PATH=$PATH:${{ github.action_path }};
        echo "${{ inputs.docker_token }}" \
          | docker login -u "${{ inputs.docker_user }}" --password-stdin \
          || error "Login to docker registry failed."
      shell: bash

    - name: Create 
      id: create
      env:
        KEEPLOG: /tmp/IMAGE
      run: |
        echo "Building containter image...";
        export PATH=$PATH:${{ github.action_path }};
        build/scripts/build \
          || error "Building docker image failed."
      shell: bash

    - name: Tag and push 
      id: tag-and-push
      env:
        IMAGE: /tmp/IMAGE
      run: |
        echo "Pushing image...";
        export PATH=$PATH:${{ github.action_path }};
        IMAGE=$(cat $IMAGE);
        docker push $IMAGE \
          || error "Pushing $IMAGE to docker registry failed."
        [ -z "${{ inputs.tag }}" ] || {
          NEWIMAGE=$(echo $IMAGE | sed 's/:.*/:'${{ inputs.tag }}'/');
          docker tag $IMAGE $NEWIMAGE \
            || error "Couldn't add tag for $IMAGE => $NEWIMAGE";
          docker push $NEWIMAGE \
            || error "Pushing $NEWIMAGE to docker registry failed."
        }
        [ -z "${{ inputs.push_also_tag }}" ] || {
          NEWIMAGE=${{ inputs.push_also_tag }};
          docker tag $IMAGE $NEWIMAGE \
            || error "Couldn't add tag for $IMAGE => $NEWIMAGE";
          docker push $NEWIMAGE \
            || error "Pushing $NEWIMAGE to docker registry failed."
        }
      shell: bash