name: 'Publish docker image'
description: 'This action publishes a docker image for valid tags'
inputs:
  push_also_tag:
    description: 'Tag to be also pushed.'
    required: false
  docker_user:
    description: 'Username with push access to docker registry.'
    required: true
  docker_token:
    description: 'Token for user with push access to docker registry.'
    required: true
  tag:
    description: 'Upload image under additional tag (e.g. latest).'
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Login to docker hub
      id: login-to-docker-hub
      run: |
        echo "Login to docker registry...";
        export PATH=$PATH:${{ github.action_path }};
        echo "${{ inputs.docker_token }}" \
          | docker login -u "${{ inputs.docker_user }}" --password-stdin \
          || error "Login to docker registry failed."
      shell: bash

    - name: Create 
      id: create
      env:
        KEEPLOG: /tmp/IMAGE
        # PATH:    $PATH:${{ github.action_path }};
      run: |
        echo "Building containter images...";
        export PATH=$PATH:${{ github.action_path }};
        echo $PATH
        build/scripts/build all || error "Building docker images failed."
      shell: bash

    - name: Push 
      id: push
      env:
        IMAGE: /tmp/IMAGE
      run: |
        export PATH=$PATH:${{ github.action_path }};
        for img in $(cat $IMAGE) ; do
          echo "Pushing image $img ...";
          docker push $img || error "Pushing $img to docker registry failed."
        done
      shell: bash