name: 'Publish docker image'
description: 'This action publishes a docker image for valid tags'
inputs:
  custom_build_script:
    description: 'Custom build script to use for building docker images (must write created images to $KEEPLOG)'
    required: true
  docker_user:
    description: 'Username with push access to docker registry.'
    required: true
  docker_token:
    description: 'Token for user with push access to docker registry.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to docker hub
      id: login-to-docker-hub
      run: |
        echo "Login to docker registry...";
        echo "${{ inputs.docker_token }}" \
          | docker login -u "${{ inputs.docker_user }}" --password-stdin \
          || error "Login to docker registry failed."
      shell: bash

    - name: Create 
      id: create
      env:
        KEEPLOG: /tmp/IMAGE
        PATH:    /usr/bin:/bin:${{ github.action_path }}
      run: |
        echo "Building containter images...";
        ${{ inputs.custom_build_script }} || error "Building docker images failed."
      shell: bash

    - name: Push 
      id: push
      env:
        IMAGE: /tmp/IMAGE
        PATH:    /usr/bin:/bin:${{ github.action_path }}
      run: |
        for img in $(cat $IMAGE) ; do
          echo "Pushing image $img ...";
          docker push $img || error "Pushing $img to docker registry failed."
        done
      shell: bash