name: Publish docker images on docker hub
run-name: Publishing docker images

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/*'
      - '.gitignore'

jobs:
  Build-and-publish-for-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Publish docker image
        uses: ./.github/actions/publish
        with:
          custom_build_script: build/scripts/build --use-version --use-cache --push
          docker_user:         ${{ secrets.DOCKER_USER }}
          docker_token:        ${{ secrets.DOCKER_TOKEN }}
