name: Publish docker images on docker hub
run-name: Publishing docker images

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/*'
      - '.gitignore'
  schedule:
    - cron: '0 0 * * *' # This line schedules the workflow to run once per day
jobs:
  Build-and-publish-for-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set custom build script
        id: vars
        run: |
          [ "${{ github.event_name }}" == "push" ] && BUILD_OPTS="--push --use-cache"
          echo "::set-output name=custom_build_script::build/scripts/build with-version $BUILD_OPTS"

      - name: Publish docker image
        uses: ./.github/actions/publish
        with:
          custom_build_script: ${{ steps.vars.outputs.custom_build_script }}
          docker_user:         ${{ secrets.DOCKER_USER }}
          docker_token:        ${{ secrets.DOCKER_TOKEN }}

