name: Testing build
run-name: Testing build (scheduled)

on:
  schedule:
    - cron: '13 23 * * *' # This line schedules the workflow to run once per day

jobs:
  Build-and-publish-for-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test build
        uses: ./.github/actions/publish
        with:
          custom_build_script: build/scripts/build --use-version --use-buildx
          docker_user:         ${{ secrets.DOCKER_USER }}
          docker_token:        ${{ secrets.DOCKER_TOKEN }}
